// SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
//
// SPDX-License-Identifier: Apache-2.0

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')

    // Fix for receive_sharing_intent using kotlin DSL without applying kotlin plugin
    // https://github.com/KasemJaffer/receive_sharing_intent/issues/XXX
    beforeEvaluate {
        if (project.name == "receive_sharing_intent") {
            if (!project.plugins.hasPlugin("org.jetbrains.kotlin.android")) {
                project.apply plugin: "org.jetbrains.kotlin.android"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

// gradle.projectsEvaluated {
//     tasks.withType(JavaCompile) {
//         options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
//     }
// }
